In [1]:
import numpy as np
from sklearn import preprocessing

# Исходная матрица наблюдений
source_matrix = np.array([[5.2, -3.1, 3.4],
                          [-1.3, 7.9, -6.2],
                          [4.0, 0.5, 2.2],
                          [7.4, -10.0, -4.6]])

# Преобразование в бинарный формат
binarized_result = preprocessing.Binarizer(threshold=2.2).transform(source_matrix)
print("\nБинаризованные данные:\n", binarized_result)

# Статистика исходных данных
print("\nИСХОДНЫЕ ДАННЫЕ:")
print("Среднее значение =", source_matrix.mean(axis=0))
print("Стандартное отклонение =", source_matrix.std(axis=0))

# Стандартизация с нулевым средним
standardized_data = preprocessing.scale(source_matrix)
print("\nПОСЛЕ СТАНДАРТИЗАЦИИ:")
print("Среднее значение =", standardized_data.mean(axis=0))
print("Стандартное отклонение =", standardized_data.std(axis=0))

# Приведение к заданному диапазону
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_minmax = minmax_scaler.fit_transform(source_matrix)
print("\nДанные после масштабирования MinMax:\n", scaled_minmax)

# Нормирование различными методами
normalized_l1 = preprocessing.normalize(source_matrix, norm='l1')
normalized_l2 = preprocessing.normalize(source_matrix, norm='l2')
print("\nНормированные данные (L1 норма):\n", normalized_l1)
print("\nНормированные данные (L2 норма):\n", normalized_l2)


Бинаризованные данные:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]

ИСХОДНЫЕ ДАННЫЕ:
Среднее значение = [ 3.825 -1.175 -1.3  ]
Стандартное отклонение = [3.20029296 6.45653738 4.16052881]

ПОСЛЕ СТАНДАРТИЗАЦИИ:
Среднее значение = [-5.55111512e-17 -5.55111512e-17 -5.55111512e-17]
Стандартное отклонение = [1. 1. 1.]

Данные после масштабирования MinMax:
 [[0.74712644 0.38547486 1.        ]
 [0.         1.         0.        ]
 [0.6091954  0.58659218 0.875     ]
 [1.         0.         0.16666667]]

Нормированные данные (L1 норма):
 [[ 0.44444444 -0.26495726  0.29059829]
 [-0.08441558  0.51298701 -0.4025974 ]
 [ 0.59701493  0.07462687  0.32835821]
 [ 0.33636364 -0.45454545 -0.20909091]]

Нормированные данные (L2 норма):
 [[ 0.74891888 -0.44647087  0.48967773]
 [-0.1283798   0.78015417 -0.61227289]
 [ 0.87100711  0.10887589  0.47905391]
 [ 0.5579228  -0.75394973 -0.34681688]]
